FROM eclipse-temurin:17-jdk

COPY --from=proto . ./proto
WORKDIR ./codesmells

# install git cli
RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

# preinstall the dependencies
COPY .mvn .mvn
COPY mvnw mvnw
COPY pom.xml pom.xml
RUN ./mvnw dependency:resolve

# copy sources and compile them in a jar
COPY src src
RUN ./mvnw package -DskipTests

ENTRYPOINT ["java","-jar", "./target/codesmells-1.0-SNAPSHOT.jar"]