FROM eclipse-temurin:17-jdk-alpine
ENV SPRING_PROFILES_ACTIVE=container

# preinstall the dependencies
COPY .mvn .mvn
COPY ./mvnw ./mvnw
COPY ./pom.xml ./pom.xml
RUN ./mvnw dependency:resolve

# copy sources and compile them in a jar
COPY ./src ./src
RUN ./mvnw package -DskipTests

ENTRYPOINT ["java","-jar", "./target/dataminer-0.0.1-SNAPSHOT.jar"]